title: uBuild Design Blocks
author: Forestry.io
email: support@forestry.io
description: >-
  ubuild-jekyll is a Jekyll theme desgined to work with Forestry's Blocks feature.
  This theme provides a set of page-level components and a pre-configured Forestry Blocks UI
  that will empower content editors to construct their own webpages.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # your site's origin, e.g. https://forestry.io
nav_items:
  -
    url: "/"
    text: "Home"
  -
    url: "lets_play.html"
    text: "Let's play"
  -
    url: "schools.html"
    text: "Schools"
  -
    url: "about_us.html"
    text: "About us"

logo: "/uploads/logo.png"
cta_url: "/en/shop.html"
cta_text: "Shop"
footer_2: "<strong>About us<br><br></strong>Ping Pong Alkmaar celebrates a wonderful
    2 years of growth since the club was set up in May 2018. The club has delivered
    multiple new initiatives over this time with its outreach programmes reaching
    out to over 6000 people in Alkmaar."
footer_3: "<strong>Weekly Session Schedule</strong><br><br>Monday – Competition Players:
    18:00 - 20:00<br>Tuesday – Early Birds: 07:00 - 08:00<br>Wednesday – Girls: 15:00
    - 16:00<br>Wednesday – Juniors: 16:15 - 17:45<br>Wednesday – Community: 19:30
    - 21:30<br>Thursday – Community: 19:30 - 21:30<br>Friday – Juniors: 16:15 - 17:45<br>Friday
    – Mini-Pingpongers: 19:30 - 21:30"
footer_4: "<address><strong>PingPong Alkmaar <br></strong><br><a href='https://www.google.nl/maps?hl=nl&amp;q=Tochtwaard+18+1824+EZ+Alkmaar'
            title='Tochtwaard 18, 1824 EZ Alkmaar'>Tochtwaard 18, 1824 EZ Alkmaar</a><br><br><a
            href='mailto:info@pingpongalkmaar.nl'>info@pingpongalkmaar.nl</a></address>"

# Build settings
defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default" # this ensures all content renders with layouts/default.html


plugins:
  - jekyll-feed
  - jekyll-menus

