title: Ping Pong Alkmaar
author: Joris Kok
email: marksmithtabletennis@gmail.com
description: Ping Pong Alkmaar
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.pingpongalkmaar.nl"
nav_items_nl:
  -
    url: "/"
    text: "Home"
  -
    url: "news.html"
    text: "Nieuws"
  -
    url: "lets_play.html"
    text: "Doe mee"
  -
    url: "help_us_grow.html"
    text: "Bouw mee"
  -
    url: "have_fun.html"
    text: "Feest mee"
  -
    url: "schools.html"
    text: "Scholen"
  -
    url: "about_us.html"
    text: "Over ons"

nav_items_en:
  -
    url: "/"
    text: "Home"
  -
    url: "news.html"
    text: "News"
  -
    url: "lets_play.html"
    text: "Let's play"
  -
    url: "help_us_grow.html"
    text: "Help us grow"
  -
    url: "have_fun.html"
    text: "Let's have fun"
  -
    url: "schools.html"
    text: "Schools"
  -
    url: "about_us.html"
    text: "About us"

logo: "/uploads/logo.png"
cta_url_nl: "/nl/shop.html"
cta_url_en: "/en/shop.html"
cta_text: "Shop"
footer_2_nl: "<strong>Over ons<br><br></strong>Ping Pong Alkmaar is de meest enthousiaste tafeltennisclub van Alkmaar en een ambitieuze sportvereniging waar iedereen welkom is"
footer_3_nl: "<strong>Weekschema</strong><br><br>Maandag – Competitie:
    18:00 - 20:00<br>Dinsdag – Vroege vogels: 07:00 - 08:00<br>Woensdag – Speciaal voor meiden: 15:00
    - 16:00<br>Woensdag – Jeugd: 16:15 - 17:45<br>Woensdag – Community: 19:30
    - 21:30<br>Vrijdag – Mini-Pingpongers: 15:00 - 16:00<br>Vrijdag
    – Jeugd: 16:15 - 17:45<br>Vrijdag - Community: 19:00 - 21:00<br><br><a target='_blank' href='/uploads/documents/agenda.xlsx'>Download de agenda</a>"
footer_4_nl: "<address><strong>Ping Pong Alkmaar <br></strong><br><a href='https://www.google.nl/maps?hl=nl&amp;q=Tochtwaard+18+1824+EZ+Alkmaar'
            title='Tochtwaard 18, 1824 EZ Alkmaar'>Tochtwaard 18, 1824 EZ Alkmaar</a><br><br><a
            href='mailto:info@pingpongalkmaar.nl'>info@pingpongalkmaar.nl</a></address><br>
            Schrijf je <a href='https://twv8tr0s1ao.typeform.com/to/U7NEbIn6' target='_blank'>hier</a> in!"
footer_2_en: "<strong>About us<br><br></strong>Ping Pong Alkmaar celebrates a wonderful
    three years of growth since the club was set up in May 2018. The club has delivered
    multiple new initiatives over this time with its outreach programmes reaching
    out to over 6000 people in Alkmaar."
footer_3_en: "<strong>Weekly Session Schedule</strong><br><br>Monday – Competition Players:
    18:00 - 20:00<br>Tuesday – Early Birds: 07:00 - 08:00<br>Wednesday – Girls: 15:00
    - 16:00<br>Wednesday – Juniors: 16:15 - 17:45<br>Wednesday – Community: 19:30
    - 21:30<br>Friday – Mini-Pingpongers: 15:00 - 16:00<br>Friday
    – Juniors: 16:15 - 17:45<br>Friday - Community: 19:00 - 21:00"
footer_4_en: "<address><strong>Ping Pong Alkmaar <br></strong><br><a href='https://www.google.nl/maps?hl=nl&amp;q=Tochtwaard+18+1824+EZ+Alkmaar'
            title='Tochtwaard 18, 1824 EZ Alkmaar'>Tochtwaard 18, 1824 EZ Alkmaar</a><br><br><a
            href='mailto:info@pingpongalkmaar.nl'>info@pingpongalkmaar.nl</a></address><br>
            Sign up <a href='https://twv8tr0s1ao.typeform.com/to/U7NEbIn6' target='_blank'>here!</a>"

# Build settings
defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default" # this ensures all content renders with layouts/default.html


plugins:
  - jekyll-feed
  - jekyll-menus

